### ISSUE TITLE
Error to run dart_snmp

### ISSUE THREAD

**Issue by lucasfmessias** [point-source/dart_snmp#1]
I have created a simple project with the example and when I tried run the code I have the error below:

Launching lib\main.dart on Chrome in debug mode...
lib\main.dart:1
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

- package:dart_snmp
- package:logging
- package:asn1lib
2

For solutions, see https://dart.dev/go/unsound-null-safety
Unhandled exception:
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:439:9)
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:146:33)
#2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:638:47)

*********************

Another attempt of run was with command "flutter run --no-sound-null-safety" but it’s also shown error:

Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety

  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
Error: Unsupported operation: InternetAddress
    at Object.throw_ [as throw] (http://localhost:62159/dart_sdk.js:5344:11)
    at Function.new (http://localhost:62159/dart_sdk.js:58997:17)
    at main (http://localhost:62159/packages/printer_check/main.dart.lib.js:18:42)
    at main.next (<anonymous>)
    at runBody (http://localhost:62159/dart_sdk.js:39221:34)
    at Object._async [as async] (http://localhost:62159/dart_sdk.js:39252:7)
    at main$ (http://localhost:62159/packages/printer_check/main.dart.lib.js:17:18)
    at main (http://localhost:62159/web_entrypoint.dart.lib.js:33:29)
    at main.next (<anonymous>)
    at http://localhost:62159/dart_sdk.js:39201:33
    at _RootZone.runUnary (http://localhost:62159/dart_sdk.js:39058:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:62159/dart_sdk.js:34044:29)
    at handleValueCallback (http://localhost:62159/dart_sdk.js:34604:49)
    at Function._propagateToListeners (http://localhost:62159/dart_sdk.js:34642:17)
    at _Future.new.[_completeWithValue] (http://localhost:62159/dart_sdk.js:34484:23)
    at http://localhost:62159/dart_sdk.js:33695:46
    at _RootZone.runUnary (http://localhost:62159/dart_sdk.js:39058:58)
    at _FutureListener.then.handleValue (http://localhost:62159/dart_sdk.js:34044:29)
    at handleValueCallback (http://localhost:62159/dart_sdk.js:34604:49)
    at Function._propagateToListeners (http://localhost:62159/dart_sdk.js:34642:17)
    at _Future.new.[_completeWithValue] (http://localhost:62159/dart_sdk.js:34484:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:62159/dart_sdk.js:34507:35)
    at Object._microtaskLoop (http://localhost:62159/dart_sdk.js:39345:13)
    at _startMicrotaskLoop (http://localhost:62159/dart_sdk.js:39351:13)
    at http://localhost:62159/dart_sdk.js:34858:9

**Comment by point-source** [comment]
Alright go ahead and give this a try and let me know how it goes: https://pub.dev/packages/dart_snmp/versions/2.0.0-dev

Thanks!

**Comment by lucasfmessias** [comment]
It worked. 

Thanks!!
